### ISSUE TITLE
Inconsistent returned value from Classifier::classify_img depending on refine parameter

### ISSUE THREAD

**Issue by easz** [martibosch/detectree#10]
The method [Classifier::classify_img](https://github.com/martibosch/detectree/blob/9d20e829cc33bb9418234514e27f20c3767c7438/detectree/classifier.py#L341) returns predicted class (**0 or 1**) from `clf.predict(X)` for `refine=False` case.
The class value is probably from the response [build_response_from_arr](https://github.com/martibosch/detectree/blob/9d20e829cc33bb9418234514e27f20c3767c7438/detectree/pixel_response.py#L59).

https://github.com/martibosch/detectree/blob/9d20e829cc33bb9418234514e27f20c3767c7438/detectree/classifier.py#L376

However, the method returns by default **0 or 255** values as tree or none-tree for `refine=True` case.
 
https://github.com/martibosch/detectree/blob/9d20e829cc33bb9418234514e27f20c3767c7438/detectree/classifier.py#L407

Is such inconsistency intended?

**Comment by martibosch** [comment]
Hello @easz,

thank you for bringing this up - I know that the code can be confusing here, but both cases (i.e., `refine=False` and `refine=True`, the latter being the default) should return the same, i.e., an array of tree and non-tree values which by default correspond to 255 and 0 [as defined in the settings](https://github.com/martibosch/detectree/blob/main/detectree/settings.py#L24-L25).

The classifier is trained to predict the two classes defined by [the `tree_val` and `nontree_val` arguments of `ClassifierTrainer.__init__`](https://github.com/martibosch/detectree/blob/main/detectree/classifier.py#L31-L32), which are forwarded to `PixelResponseBuilder.__init__` (see [lines 112-114](https://github.com/martibosch/detectree/blob/main/detectree/classifier.py#L112-L114) and [lines 210-212](https://github.com/martibosch/detectree/blob/main/detectree/classifier.py#L210-L212) of `classifier.py`). The default `None` values for the arguments means that [they will be ultimately taken from the settings](https://github.com/martibosch/detectree/blob/main/detectree/pixel_response.py#L36-L42).

Therefore, in your first snippet (`refine=False`), the method `clf.predict` will return an array of the `tree_val` and `nontree_val` values provided in `ClassifierTrainer.__init__` as explained above. The second snippet uses [the `tree_val` and `nontree_val` argument values provided in `Classifier.__init__`](https://github.com/martibosch/detectree/blob/main/detectree/classifier.py#L276-L277), which if left as `None` (default) will also correspond to the 255 and 0 values from the settings. I now actually realize that these arguments are not necessary in `Classifier` since they [can be retrieved from the `clf.classes_` attribute (since `clf` is an instance of `sklearn.ensemble.AdaBoostClassifier`)](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html). I will update the code accordingly in the next release.

I hope that this addresses your question. I will close this issue as soon as I update the code as described above. Best,
Martí

**Comment by martibosch** [comment]
Hello again,

I have actually realized that as far as I am concerned, there is no deterministic way to know which values of `clf.classes_` (where `clf` is a trained instance of `sklearn.ensemble.AdaBoostClassifier`) correspond to a tree and non tree pixel. If anyone knows of a way to properly retrieve the tree and non tree class values, I would gladly reopen this and update the `Classifier` class so that it does not need such information in the initialization. In the meantime, I am closing this issue.

Feel free to reoopen it if needed. Thank you again for using detectree. Best,
Martí
