### ISSUE TITLE
Bug in train_test_split.py

### ISSUE THREAD

**Issue by pedromarcolin** [martibosch/detectree#7]
Hello !

I'm trying to reproduce the detectree code in my computer, but I'm receiving an error when I execute this line of the background code: 

split_df, evr = ts.train_test_split(method='cluster-II',
                                    num_components=12,
                                    return_evr=True)

This line is giving the error showed below:

AttributeError: 'TrainingSelector' object has no attribute '_descr_feature_matrix'

What am I doing wrong?

**Comment by pedromarcolin** [comment]
@martibosch 

I executed this code that you mentioned: conda install -c conda-forge make . After, I executed the cells of the background, but when I execute this line: !make tiles, appears for me this error: 

![image](https://user-images.githubusercontent.com/70024461/91110738-1bb9ee00-e655-11ea-85c0-9440e4321874.png)

The full code is showed bellow:

![image](https://user-images.githubusercontent.com/70024461/91110770-2e342780-e655-11ea-8d83-5e8362eb0207.png)

Another error is the command "bash", that the program doesn't recognise.

I hope you could help me out on this issues. 

Best regards,

Pedro Marcolin

**Comment by pedromarcolin** [comment]
Sorry, the full code is showed bellow:

![image](https://user-images.githubusercontent.com/70024461/91110838-5a4fa880-e655-11ea-8a69-771441062e36.png)
![image](https://user-images.githubusercontent.com/70024461/91110858-676c9780-e655-11ea-9b1e-7d480c607eb9.png)

**Comment by pedromarcolin** [comment]
Hello Martí !

I executed this line: **conda install -c conda-forge make**, that's ok.

I'm having some troubles executing this lines of the codes:

![image](https://user-images.githubusercontent.com/70024461/91239509-18d30200-e716-11ea-8dbb-1fae3a0b8c1e.png)

![image](https://user-images.githubusercontent.com/70024461/91239539-3011ef80-e716-11ea-9d50-22c7618ea894.png)

In both cases appears this website to download the item ortho_sommer14.prj, but when I click on this, appears this website:

![image](https://user-images.githubusercontent.com/70024461/91239643-85e69780-e716-11ea-893f-e7cd885a7f0f.png)

and I couldn't download the file.

**Comment by martibosch** [comment]
Hello Pedro,

I wonder whether these file not found errors are because of the different path syntax in UNIX and Windows (i.e., the use of the `/` and `\` directory separators respectively). I believe that you can get more compatibility with UNIX commands in Windows by using Cygwin. Maybe such commands will work if you try running the Jupyter notebooks like this:
https://www.scivision.dev/install-ipython-jupyter-in-cygwin/

On the other hand, the `ortho_sommer14.prj` is a basically text-like file with the contents that you see displayed in the browser - therefore, if you encounter problems downloading the file, you can instead copy such text into the notepad or any text editor and save it as `ortho_sommer14.prj` in the right path.

Best,
Martí

**Comment by martibosch** [comment]
Hello Pedro,

have there been any news regarding this issue? Otherwise, may I close it?

Best,
Martí

**Comment by pedromarcolin** [comment]
Hello Marti !

Sorry about the late, there's no issues anymore, you can close it.

Best regards,

Pedro Marcolin
