### ISSUE TITLE
Custom weights for training my model

### ISSUE THREAD

**Issue by Ayushri** [martibosch/detectree#8]
Hi,
I have one query regarding this repo.
This has a pretrained classifier on aerial images of trees right?
I wanted to try utilizing the custom weights of this pretrained classifier along with my custom data to train another model. 
How can I do that(I mean how to get the custom weights)?

**Comment by martibosch** [comment]
Hello @Ayushri,

thank you for your interest in detectree. I currently have classifiers trained from a variety of scenes (summer aerial imagery) in Geneva, Lausanne and Zurich (which are all quite similar). I am happy to provide them to you (as joblib files), just note that they are quite specific to their training data. I'd say there are two things to consider:

* **The overall look of the images**: the classifier will likely not work very well if your imagery data is visually too different from the training data (e.g., the colors and shapes of the trees, background soil cover colors, etc.). In the 11th cell of [this notebook](https://github.com/martibosch/detectree-example/blob/master/notebooks/cluster-I.ipynb), you can actually see the 3 images that have been used to train classifier. If your images do not look to different, you might give it a try.
* **Resolution**: many of the texture-based features are scale-dependent and hence influenced by the resolution of the imagery. The resolution of the training data for the classifier is 0.5m, so ideally your resolution should be as close as possible to that (otherwise, you might try resampling your images). Alternatively, I can also provide you another classifier based on 1m imagery (i.e., from the [lausanne-tree-canopy](https://github.com/martibosch/lausanne-tree-canopy) repository.

From the joblib file, you might do:

```python
import detectree as dtr
import joblib as jl

clf = jl.load('path/to/classifier.joblib')
pred_arr = dtr.classify_img('path/to/aerial-image.tif', clf, output_filepath='path/to/output-canopy.tif')
```
Note that `pred_arr` will be a numpy array that corresponds to the classified image (that will be dumped to `output_filepath` if provided), see [the docs for `classify_img` for more details](https://github.com/martibosch/detectree/issues/8https://detectree.readthedocs.io/en/latest/pixel_classification.html#detectree.Classifier.classify_img).

I hope this helps. Let me know if you want the classifier and I will send you the joblib file. Best,
Martí

**Comment by martibosch** [comment]
I am closing this, feel free to reopen if needed, and let me know if you still want me to send you the joblib files. Best,
Martí

**Comment by easz** [comment]
> thank you for your interest in detectree. I currently have classifiers trained from a variety of scenes (summer aerial imagery) in Geneva, Lausanne and Zurich (which are all quite similar). I am happy to provide them to you (as joblib files), just note that they are quite specific to their training data. I'd say there are two things to consider:

Hi, are such pre-trained models (joblib files) already included in the repository?
I see only some in `test` folder and am not sure if they are the right one.

**Comment by martibosch** [comment]
Hello @easz,

no, these joblib files are not included in the repository (the ones used for the tests are just to test function argument types and data structures but they have not been properly trained). You can use the code from the [`detectree-example`](https://github.com/martibosch/detectree-example) to obtain trained weights, or I could send them to you (e.g., by mail). In any case, note my remarks [in the comment above](https://github.com/martibosch/detectree/issues/8#issuecomment-821753571) about these pre-trained weights.

Let me know what works best for you. Best,
Martí

**Comment by PradeepYLN** [comment]
Hi @martibosch  Thank you for sharing the code. I would like to generate a forest ground truth map using your repository using Google satellite images. could you please share the weights that are trained with 0.5m images?
Thanks in advance.
